---
ID: "312d7c17-815f-4020-8eea-8cf721ee2418"
Parent: "4f00880e-dfce-40df-ac79-aa0b3025540b"
Template: "9f7eb765-4566-4dd5-b74f-8bba6a27ba17"
Path: "/sitecore/content/industry-verticals/nova-medical/Settings/Theme Settings"
SharedFields:
- ID: "38c79e1a-489b-431d-b04e-aefea3c09438"
  Hint: FontOptions
  Value: |
    [
      {
        "label": "Sans Serif",
        "suffix": ", sans-serif",
        "fonts": [
          {
            "name": "Anton",
            "link": "https://fonts.googleapis.com/css2?family=Anton&display=swap"
          },
          {
            "name": "Bebas Neue",
            "link": "https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap"
          },
          {
            "name": "Inter",
            "link": "https://fonts.googleapis.com/css2?family=Inter:wght@100..900&display=swap"
          },
          {
            "name": "Lato",
            "link": "https://fonts.googleapis.com/css2?family=Lato:wght@100..900&display=swap"
          },
          {
            "name": "Manrope",
            "link": "https://fonts.googleapis.com/css2?family=Manrope:wght@200..800&display=swap"
          },
          {
            "name": "Montserrat",
            "link": "https://fonts.googleapis.com/css2?family=Montserrat:wght@100..900&display=swap"
          },
          {
            "name": "Mulish",
            "link": "https://fonts.googleapis.com/css2?family=Mulish:ital,wght@0,200..1000;1,200..1000&display=swap"
          },
          {
            "name": "Noto Sans",
            "link": "https://fonts.googleapis.com/css2?family=Noto+Sans:ital,wght@0,100..900;1,100..900&display=swap"
          },
          {
            "name": "Nunito",
            "link": "https://fonts.googleapis.com/css2?family=Nunito:wght@200..1000&display=swap"
          },
          {
            "name": "Open Sans",
            "link": "https://fonts.googleapis.com/css2?family=Open+Sans:wght@300..800&display=swap"
          },
          {
            "name": "Oswald",
            "link": "https://fonts.googleapis.com/css2?family=Oswald:wght@200..700&display=swap"
          },
          {
            "name": "Poppins",
            "link": "https://fonts.googleapis.com/css2?family=Poppins:wght@100..900&display=swap"
          },
          {
            "name": "Roboto",
            "link": "https://fonts.googleapis.com/css2?family=Roboto:wght@100..900&display=swap"
          },
          {
            "name": "Rubik",
            "link": "https://fonts.googleapis.com/css2?family=Rubik:wght@300..900&display=swap"
          }
        ]
      },
      {
        "label": "Serif",
        "suffix": ", serif",
        "fonts": [
          {
            "name": "Abril Fatface",
            "link": "https://fonts.googleapis.com/css2?family=Abril+Fatface&display=swap"
          },
          {
            "name": "Cormorant",
            "link": "https://fonts.googleapis.com/css2?family=Cormorant:wght@300..700&display=swap"
          },
          {
            "name": "Libre Baskerville",
            "link": "https://fonts.googleapis.com/css2?family=Libre+Baskerville:ital,wght@0,400..700;1,400..700&display=swap"
          },
          {
            "name": "Lora",
            "link": "https://fonts.googleapis.com/css2?family=Lora:wght@400..700&display=swap"
          },
          {
            "name": "Merriweather",
            "link": "https://fonts.googleapis.com/css2?family=Merriweather:wght@300..900&display=swap"
          },
          {
            "name": "Playfair Display",
            "link": "https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400..900&display=swap"
          },
          {
            "name": "Roboto Serif",
            "link": "https://fonts.googleapis.com/css2?family=Roboto+Serif:wght@100..900&display=swap"
          }
        ]
      },
      {
        "label": "Monospace",
        "suffix": ", monospace",
        "fonts": [
          {
            "name": "Fira Code",
            "link": "https://fonts.googleapis.com/css2?family=Fira+Code:wght@300..700&display=swap"
          },
          {
            "name": "Roboto Mono",
            "link": "https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@100..700&display=swap"
          },
          {
            "name": "Source Code Pro",
            "link": "https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@200..900&display=swap"
          },
          {
            "name": "Space Mono",
            "link": "https://fonts.googleapis.com/css2?family=Space+Mono:wght@400..700&display=swap"
          }
        ]
      },
      {
        "label": "Display",
        "suffix": ", cursive",
        "fonts": [
          {
            "name": "Great Vibes",
            "link": "https://fonts.googleapis.com/css2?family=Great+Vibes&display=swap"
          },
          {
            "name": "Pacifico",
            "link": "https://fonts.googleapis.com/css2?family=Pacifico&display=swap"
          },
          {
            "name": "Satisfy",
            "link": "https://fonts.googleapis.com/css2?family=Satisfy&display=swap"
          }
        ]
      }
    ]
    
- ID: "bd13b584-36a1-4c4e-aa1c-b4689ee2fae8"
  Hint: CustomCSS
  Value: |
    --color-background: #ffffff;
    --color-background-secondary: #f4fdfd;
    --color-background-tertiary: #b8eff2;
    --color-foreground: #004875;
    --color-background-dark: #011119;
    --color-background-secondary-dark: #047294;
    --color-background-tertiary-dark: #023859;
    --color-foreground-dark: #ffffff;
    --color-foreground-secondary-dark: #b8eff2;
    --color-accent: #6cd8c9;
    --color-accent-muted: #a3ddcf;
    --color-background-input: #e7f7f4;
    --color-disabled: #dcdcdc;
    --color-disabled-dark: #70a7b8;
    --color-border: #e8e8e8;
    --font-heading: 'Mulish', sans-serif;
    --font-body: 'Noto Sans', sans-serif;
    --radius-base: 0.5rem;
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "51a0ffd5-2ff7-416b-ae20-1bd14d6ce5e4"
- ID: "f4f80dc4-7985-4bba-a11e-4daebba94481"
  Hint: ThemeDefaults
  Value: |
    --color-background: #ffffff;
    --color-background-secondary: #f4fdfd;
    --color-background-tertiary: #b8eff2;
    --color-foreground: #023859;
    
    --color-background-dark: #011119;
    --color-background-secondary-dark: #047294;
    --color-background-tertiary-dark: #023859;
    --color-foreground-dark: #ffffff;
    --color-foreground-secondary-dark: #b8eff2;
    
    --color-accent: #6cd8c9;
    --color-accent-muted: #a3ddcf;
    
    --color-background-input: #e7f7f4;
    --color-disabled: #dcdcdc;
    --color-disabled-dark: #70a7b8;
    
    --color-border: #e8e8e8;
    
    --font-heading: 'Mulish', sans-serif;
    --font-body: 'Noto Sans', sans-serif;
    
    --radius-base: 0.5rem;
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20251117T220631Z
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "ff03e5cf-ded2-48a3-9cb5-1a2f4cc4864a"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\n4H0zdVBa8osGkMA2YP2mMjQBpCnKAcn
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260114T211748Z
- Language: "es-MX"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20251117T220631Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\jeffrey.isham@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\jeffrey.isham@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "0495fc08-43da-4311-9211-eb24c5fe55cf"
    - ID: "9857f526-390f-48df-b6d1-1a97cc328e8f"
      Hint: __Version Name
      Value: AI translated
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\brandon.bruno@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260114T193402Z
  - Version: 2
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20251117T220631Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\jeffrey.isham@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\jeffrey.isham@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "a454b309-c31c-44a9-99c1-08fcbee45e42"
    - ID: "9857f526-390f-48df-b6d1-1a97cc328e8f"
      Hint: __Version Name
      Value: AI translated
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\brandon.bruno@sitecore.com
    - ID: "c8f93afe-bfd4-4e8f-9c61-152559854661"
      Hint: __Valid from
      Value: 
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260116T155000Z
  - Version: 3
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260318T171056Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\jeffrey.isham@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\brandon.bruno@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "7aa1c899-2b84-43c0-a18e-07029f5f5267"
    - ID: "9857f526-390f-48df-b6d1-1a97cc328e8f"
      Hint: __Version Name
      Value: AI translated
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\brandon.bruno@sitecore.com
    - ID: "c8f93afe-bfd4-4e8f-9c61-152559854661"
      Hint: __Valid from
      Value: 20260318T171056Z
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260318T171056Z
  - Version: 4
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260319T132013Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\jeffrey.isham@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\brandon.bruno@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "3bf56d60-4686-49e0-ac02-39690c3e31e7"
    - ID: "9857f526-390f-48df-b6d1-1a97cc328e8f"
      Hint: __Version Name
      Value: AI translated
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\brandon.bruno@sitecore.com
    - ID: "c8f93afe-bfd4-4e8f-9c61-152559854661"
      Hint: __Valid from
      Value: 20260319T132013Z
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260319T132013Z
  - Version: 5
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260325T140726Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\jeffrey.isham@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\brandon.bruno@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "38f46f5c-bd51-4ca1-8cbc-5510d13f996f"
    - ID: "9857f526-390f-48df-b6d1-1a97cc328e8f"
      Hint: __Version Name
      Value: AI translated
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\brandon.bruno@sitecore.com
    - ID: "c8f93afe-bfd4-4e8f-9c61-152559854661"
      Hint: __Valid from
      Value: 20260325T140726Z
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260325T140726Z
  - Version: 6
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260327T172736Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\jeffrey.isham@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\brandon.bruno@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "17e9997a-7bbd-42e0-9c11-4345cfece6a6"
    - ID: "9857f526-390f-48df-b6d1-1a97cc328e8f"
      Hint: __Version Name
      Value: AI translated
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\brandon.bruno@sitecore.com
    - ID: "c8f93afe-bfd4-4e8f-9c61-152559854661"
      Hint: __Valid from
      Value: 20260327T172736Z
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260327T172736Z
  - Version: 7
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260331T123638Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\jeffrey.isham@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\brandon.bruno@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "d91f7203-629e-42ad-bec9-0aea66967e01"
    - ID: "9857f526-390f-48df-b6d1-1a97cc328e8f"
      Hint: __Version Name
      Value: AI translated
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\brandon.bruno@sitecore.com
    - ID: "c8f93afe-bfd4-4e8f-9c61-152559854661"
      Hint: __Valid from
      Value: 20260331T123638Z
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260331T123638Z
  - Version: 8
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20251117T220631Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\jeffrey.isham@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\jeffrey.isham@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "151b62e7-df68-4e86-88e1-8b9784c5641e"
    - ID: "9857f526-390f-48df-b6d1-1a97cc328e8f"
      Hint: __Version Name
      Value: 
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\brandon.bruno@sitecore.com
    - ID: "c8f93afe-bfd4-4e8f-9c61-152559854661"
      Hint: __Valid from
      Value: 
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260407T120430Z
- Language: "es-PR"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260327T185029Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\brandon.bruno@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\brandon.bruno@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "7c8e2314-7b1c-43ae-a310-5efdf7c826a5"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\brandon.bruno@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260327T185029Z
- Language: "ko-KR"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260320T191731Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\brandon.bruno@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\brandon.bruno@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "62151184-b086-47bc-a6e3-2a9dea72e70c"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\brandon.bruno@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260320T191731Z
- Language: "zh-CN"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260327T154903Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\brandon.bruno@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\brandon.bruno@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "4151648c-3e2c-4723-ba66-61b4b5e26c3f"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\brandon.bruno@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260327T154903Z
  - Version: 2
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260330T145200Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\brandon.bruno@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\brandon.bruno@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "d745c50a-7c34-4e0e-824a-bb501d944716"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\brandon.bruno@sitecore.com
    - ID: "c8f93afe-bfd4-4e8f-9c61-152559854661"
      Hint: __Valid from
      Value: 20260330T145200Z
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260330T145200Z
